set nocompatible

syntax enable                   " enable syntax highlighting
set encoding=utf-8
set background=dark             " indicates that I use a dark background
set visualbell                  " disable audible bell

set showcmd                     " display incomplete commands
set cursorline                  " highlight the current line
set ruler                       " show the cursor position all the time
set list                        " show invisible characters

set noswapfile                  " don't save swap files

"" List chars
set listchars=""                " Reset the listchars
set listchars=tab:\ \           " a tab should display as "  ", trailing whitespace as "."
set listchars+=trail:-          " show trailing spaces as dashes

"" Searching
set nohlsearch                  " don't highlight search matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

set pastetoggle=<F10>           " F10 to toggle paste mode

set wildignore+=*.gif,*.png,*.jpg,*.jpeg,*.bmp,*.tiff,*.psd,*.svg,*.woff,*.eot,*.ttf

set autoread                    " when a file's content's have changed, automatically load it again
