[settings]
idiomatic_version_file = true
idiomatic_version_file_enable_tools = ["go"]

[tools]
awscli = { version = "latest", symlink_bins = "true" }
gcloud = "latest"
go = "latest"
golangci-lint = "v2.11.4"
node = "24"
pipx = "latest"
python = "3.13"
rust = "latest"
terraform = "1.14.9"
usage = "latest"
